USE TourifyDb;
UPDATE [HomePages] SET [Title1] = N'You Like To Go?';
UPDATE [HomePages] SET [Title2] = N'Let''s The World Together!';
UPDATE [HomePages] SET [Title3] = N'Find Your Perfect Tour At Travel';
UPDATE [HomePages] SET [Description] = N'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s,';
UPDATE [HomePages] SET [HomeButtonText] = NULL;
UPDATE [HomePages] SET [HomeAboutTitle] = N'Welcome to Travela';
UPDATE [HomePages] SET [HomeAboutDescription] = N'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias, dolorum, doloribus sunt dicta, officia voluptatibus libero necessitatibus natus impedit quam ullam assumenda? Id atque iste consectetur. Commodi odit ab saepe!  Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium quos voluptatem suscipit neque enim, doloribus ipsum rem eos distinctio, dignissimos nisi saepe nulla? Libero numquam perferendis provident placeat molestiae quia?';
UPDATE [BookPages] SET [BookDescription] = N'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur maxime ullam esse fuga blanditiis accusantium pariatur quis sapiente, veniam doloribus praesentium? Repudiandae iste voluptatem fugiat doloribus quasi quo iure officia.';
UPDATE [BookPages] SET [BookFormDescription] = N'Get On Your First Adventure Trip With Travela. Get More Deal Offers Here.';
UPDATE [Services] SET [Service1Description] = N'Dolor sit amet consectetur adipisicing elit. Non alias eum, suscipit expedita corrupti officiis debitis possimus nam laudantium beatae quidem dolore consequuntur voluptate rem reiciendis, omnis sequi harum earum.';
UPDATE [Services] SET [Service2Description] = N'Dolor sit amet consectetur adipisicing elit. Non alias eum, suscipit expedita corrupti officiis debitis possimus nam laudantium beatae quidem dolore consequuntur voluptate rem reiciendis, omnis sequi harum earum.';
UPDATE [Services] SET [Service3Description] = N'Dolor sit amet consectetur adipisicing elit. Non alias eum, suscipit expedita corrupti officiis debitis possimus nam laudantium beatae quidem dolore consequuntur voluptate rem reiciendis, omnis sequi harum earum.';
UPDATE [Services] SET [Service4Description] = N'Dolor sit amet consectetur adipisicing elit. Non alias eum, suscipit expedita corrupti officiis debitis possimus nam laudantium beatae quidem dolore consequuntur voluptate rem reiciendis, omnis sequi harum earum.';
UPDATE [Services] SET [Service1Icon] = N'fa fa-globe fa-4x text-primary';
UPDATE [Services] SET [Service2Icon] = N'fa fa-hotel fa-4x text-primary';
UPDATE [Services] SET [Service3Icon] = N'fa fa-user fa-4x text-primary';
UPDATE [Services] SET [Service4Icon] = N'fa fa-cog fa-4x text-primary';
UPDATE [ContactPages] SET [ContactLocationIcon] = N'fa fa-map-marker-alt fa-3x text-primary';
UPDATE [ContactPages] SET [ContactPhoneIcon] = N'fa fa-phone-alt fa-3x text-primary mb-3';
UPDATE [ContactPages] SET [ContactEmailIcon] = N'fa fa-envelope-open fa-3x text-primary mb-3';
UPDATE [TourPages] SET [TourTitle] = N'Lets get a tour';
UPDATE [GalleryPages] SET [GalleryTitle] = N'Lets look our Memories';
UPDATE [GalleryPages] SET [GalleryDescription] = NULL;
UPDATE [GalleryItems] SET [Title] = N'Turkeyyy' WHERE [Id] = '9CECB6F0-54CB-4103-B681-EB8537FE7BC1';

UPDATE [GalleryItems] SET [Title] = N'The Romantic Eyfel Tower' WHERE [Title] = N'The Romantic Eiffel Tower';
UPDATE [HomePages] SET [HomeDestinationButtonText] = N'Lets Find Your Tour Destination';
UPDATE [AboutPages] SET [AboutGuideDescription] = N'Our travel guides bring local Insight, calm planning, and better stories to every destination';
