// <auto-generated />
using System;
using KJ.Tourify.WebUI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KJ.Tourify.WebUI.Migrations
{
    [DbContext(typeof(TourifyDbContext))]
    partial class TourifyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KJ.Tourify.WebUI.Models.Entities.AboutPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AboutDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutGuideButtonText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutGuideDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutGuideTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutHeader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutUpperTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AboutPages");
                });

            modelBuilder.Entity("KJ.Tourify.WebUI.Models.Entities.BookPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BookButtonText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookFormButtonText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookFormDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookFormTittle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookHeader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookUpperTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BookPages");
                });

            modelBuilder.Entity("KJ.Tourify.WebUI.Models.Entities.ContactPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactButtonText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmailIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmailTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactHeader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactLocationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactLocationIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactLocationTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactMapUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhoneIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhoneTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactSubTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactUpperTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactPages");
                });

            modelBuilder.Entity("KJ.Tourify.WebUI.Models.Entities.CreateTestimonialPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateTestimonialButtonText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateTestimonialDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateTestimonialDescription1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateTestimonialDescription2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateTestimonialDescription3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateTestimonialHeader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateTestimonialIcon1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateTestimonialIcon2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateTestimonialIcon3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateTestimonialSubTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateTestimonialTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateTestimonialTitle1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateTestimonialTitle2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateTestimonialTitle3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateTestimonialUpperTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CreateTestimonialPages");
                });

            modelBuilder.Entity("KJ.Tourify.WebUI.Models.Entities.GalleryCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GalleryPageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GalleryPageId");

                    b.ToTable("GalleryCategories");
                });

            modelBuilder.Entity("KJ.Tourify.WebUI.Models.Entities.GalleryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GalleryCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GalleryImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("GalleryPageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GalleryCategoryId");

                    b.HasIndex("GalleryPageId");

                    b.ToTable("GalleryItems");
                });

            modelBuilder.Entity("KJ.Tourify.WebUI.Models.Entities.GalleryPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GalleryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GalleryHeader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GalleryTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GalleryUpperTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GalleryPages");
                });

            modelBuilder.Entity("KJ.Tourify.WebUI.Models.Entities.GuidePage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GuideDescription1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuideDescription2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuideDescription3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuideDescription4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuideHeader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuideImageUrl1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuideImageUrl2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuideImageUrl3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuideImageUrl4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuideName1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuideName2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuideName3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuideName4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuideTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuideUpperTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Guides");
                });

            modelBuilder.Entity("KJ.Tourify.WebUI.Models.Entities.HomePage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeAboutButtonText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeAboutDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeAboutFeatures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeAboutImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeAboutService1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeAboutService2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeAboutService3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeAboutService4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeAboutServicesButtonText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeAboutServicesTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeAboutTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeAboutUpperTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeButtonText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeDestinationButtonText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeDestinationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomePageDestinationTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpperTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HomePages");
                });

            modelBuilder.Entity("KJ.Tourify.WebUI.Models.Entities.ServicePage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Service1Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service1Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service1Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service2Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service2Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service2Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service3Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service3Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service3Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service4Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service4Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service4Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceHeader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServicePageButtonText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceUpperTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("KJ.Tourify.WebUI.Models.Entities.Subscribe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpperTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subscribe");
                });

            modelBuilder.Entity("KJ.Tourify.WebUI.Models.Entities.TourCity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TourCities");
                });

            modelBuilder.Entity("KJ.Tourify.WebUI.Models.Entities.TourItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreateTestimonialPageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HowMuchMoney")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TourCityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TourDay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TourImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TourLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TourPageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TourPerson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreateTestimonialPageId");

                    b.HasIndex("TourCityId");

                    b.HasIndex("TourPageId");

                    b.ToTable("TourItems");
                });

            modelBuilder.Entity("KJ.Tourify.WebUI.Models.Entities.TourPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TourHeader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TourTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TourUpperTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TourPages");
                });

            modelBuilder.Entity("KJ.Tourify.WebUI.Models.Entities.TourTestimonialItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TourItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TourItemId");

                    b.ToTable("TourTestimonialItems");
                });

            modelBuilder.Entity("KJ.Tourify.WebUI.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KJ.Tourify.WebUI.Models.Entities.GalleryCategory", b =>
                {
                    b.HasOne("KJ.Tourify.WebUI.Models.Entities.GalleryPage", "GalleryPage")
                        .WithMany("GalleryCategories")
                        .HasForeignKey("GalleryPageId");

                    b.Navigation("GalleryPage");
                });

            modelBuilder.Entity("KJ.Tourify.WebUI.Models.Entities.GalleryItem", b =>
                {
                    b.HasOne("KJ.Tourify.WebUI.Models.Entities.GalleryCategory", "GalleryCategory")
                        .WithMany("GalleryItems")
                        .HasForeignKey("GalleryCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KJ.Tourify.WebUI.Models.Entities.GalleryPage", "GalleryPage")
                        .WithMany("GalleryItems")
                        .HasForeignKey("GalleryPageId");

                    b.Navigation("GalleryCategory");

                    b.Navigation("GalleryPage");
                });

            modelBuilder.Entity("KJ.Tourify.WebUI.Models.Entities.TourItem", b =>
                {
                    b.HasOne("KJ.Tourify.WebUI.Models.Entities.CreateTestimonialPage", "CreateTestimonialPage")
                        .WithMany("TourItems")
                        .HasForeignKey("CreateTestimonialPageId");

                    b.HasOne("KJ.Tourify.WebUI.Models.Entities.TourCity", "City")
                        .WithMany("TourItems")
                        .HasForeignKey("TourCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KJ.Tourify.WebUI.Models.Entities.TourPage", "TourPage")
                        .WithMany("TourItems")
                        .HasForeignKey("TourPageId");

                    b.Navigation("City");

                    b.Navigation("CreateTestimonialPage");

                    b.Navigation("TourPage");
                });

            modelBuilder.Entity("KJ.Tourify.WebUI.Models.Entities.TourTestimonialItem", b =>
                {
                    b.HasOne("KJ.Tourify.WebUI.Models.Entities.TourItem", "TourItem")
                        .WithMany("TourTestimonialItems")
                        .HasForeignKey("TourItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TourItem");
                });

            modelBuilder.Entity("KJ.Tourify.WebUI.Models.Entities.CreateTestimonialPage", b =>
                {
                    b.Navigation("TourItems");
                });

            modelBuilder.Entity("KJ.Tourify.WebUI.Models.Entities.GalleryCategory", b =>
                {
                    b.Navigation("GalleryItems");
                });

            modelBuilder.Entity("KJ.Tourify.WebUI.Models.Entities.GalleryPage", b =>
                {
                    b.Navigation("GalleryCategories");

                    b.Navigation("GalleryItems");
                });

            modelBuilder.Entity("KJ.Tourify.WebUI.Models.Entities.TourCity", b =>
                {
                    b.Navigation("TourItems");
                });

            modelBuilder.Entity("KJ.Tourify.WebUI.Models.Entities.TourItem", b =>
                {
                    b.Navigation("TourTestimonialItems");
                });

            modelBuilder.Entity("KJ.Tourify.WebUI.Models.Entities.TourPage", b =>
                {
                    b.Navigation("TourItems");
                });
#pragma warning restore 612, 618
        }
    }
}
